### ISSUE TITLE
Can you add an option to only show notify which is Participating?

### ISSUE THREAD

**Issue by stardiviner** [xuchunyang/github-notifier.el#1]
As the title said.

**Comment by stardiviner** [comment]
I found you use `url-request-extra-headers`, Maybe you can make it customible with `defcustom`? Or define a new option `github-notifier-type-participation`?

**Comment by xuchunyang** [comment]
> As the title said.

Yes, according to [Github's API doc](https://developer.github.com/v3/activity/notifications/#list-your-notifications), `GET /notifications?participating=true` should do the task, I will implement this tonight.

> I found you use url-request-extra-headers, Maybe you can make it customible with defcustom? Or define a new option github-notifier-type-participation?

Not really, I let-bind this variable, so its value won't be change by this package, and I don't think user want to custom this variable since it's not even a user option (that is, not defined with `defcustom`).

**Comment by xuchunyang** [comment]
Now you can use `(setq github-notifier-only-participating t)`, the variable defaults to `nil`.

**Comment by stardiviner** [comment]
thanks
